Repository camptocamp/helm-geoserver-cloud, pull requests merged in 2023-03, with the labels that each got.

#118 Migrate to custom pod library
  .github/changelog-config.yaml
  .github/workflows/auto-review.yaml
  .github/workflows/changelog.yaml
  .github/workflows/main.yaml
  .github/workflows/pr-checks.yaml
  Chart.yaml
  Makefile
  README.md
  examples/README.md
  examples/common/Chart.yaml
  examples/common/templates/cm_db_jndi.yaml
  examples/common/templates/pv_pvc.yaml
  examples/common/values.yaml
  examples/datadir/Chart.yaml
  examples/datadir/values.yaml
  examples/jdbc/Chart.yaml
  examples/jdbc/templates/secrets_db.yaml
  examples/jdbc/values.yaml
  templates/config/configmap.yaml
  templates/gateway/deployment.yaml
  templates/gateway/service.yaml
  templates/generic/service_and_deployment.yaml
  templates/ingress.yaml
  templates/secrets/secret_postgres.yaml
  templates/serviceaccount.yaml
  tests/chart/Chart.yaml
  tests/chart/values.yaml
  tests/expected-common.yaml
  tests/expected-datadir.yaml
  tests/expected-jdbc.yaml
  tests/expected.yaml
  tests/xml/postgis_store.xml
  values.yaml
Labels: refactor

#120 Cleanup
  examples/README.md
  values.yaml
Labels: enhancement

#121 Update readme
  README.md
Labels: documentation

#124 Upgrade custom pod
  Chart.yaml
Labels: bug
